### ISSUE TITLE
Homepage typo?

### ISSUE THREAD

**Issue by benepo** [ArangoGutierrez/singularity-go#1]
The homepage says

> equivalent of:
> 
> at the command prompt:

Is the "equivalent of" reference missing?

P.S. Great job improving the Go portability!

**Comment by ArangoGutierrez** [comment]
Thanks @benepo , hope this will be solved on the next commit.
also PR's are welcome!

**Comment by ArangoGutierrez** [comment]
Fixed with commit 55f3142db67cbfbfd66568cade8ddb8b9c9a39a9

Closing issues #1
